// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using BaseContextExampleApp.Models;
using EntityLibrary;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace BaseContextExampleApp.Data;

public partial class Context : ProtoTypeContext
{
    public Context()
    {
        
    }
    public virtual DbSet<BirthDays> BirthDays { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BirthDays>(entity =>
        {
            entity.Property(e => e.YearsOld).HasComputedColumnSql("((CONVERT([int],format(getdate(),'yyyyMMdd'))-CONVERT([int],format([BirthDate],'yyyyMMdd')))/(10000))", false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}