// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace SpreadSheetLightTableSample.Models;

[Table("ContactTypes")]
public partial class ContactTypes
{
    public int Identifier { get; set; }

    public string ContactType { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();
}