// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ConsoleConfigurationLibrary.Classes;
using ConsoleConfigurationLibrary.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace SpreadSheetLightTableSample.Models;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<ContactTypes> ContactTypes { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Gender> Genders { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetMainConnectionString());

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ContactTypes>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.Property(e => e.ContactType)
                .HasMaxLength(50)
                .HasColumnName("ContactType");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.Identifier);

            entity.ToTable("Customer");

            entity.Property(e => e.CompanyName).HasMaxLength(255);
            entity.Property(e => e.ContactFirstName).HasMaxLength(255);
            entity.Property(e => e.ContactLastName).HasMaxLength(255);

            entity.HasOne(d => d.ContactTypeIdentifierNavigation).WithMany(p => p.Customers)
                .HasForeignKey(d => d.ContactTypeIdentifier)
                .HasConstraintName("FK_Customer_ContactTypes");

            entity.HasOne(d => d.GenderIdentifierNavigation).WithMany(p => p.Customers)
                .HasForeignKey(d => d.GenderIdentifier)
                .HasConstraintName("FK_Customer_Genders");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);


    private static string GetMainConnectionString()
        => Config.Configuration.JsonRoot()
            .GetSection(nameof(ConnectionStrings))
            .Get<ConnectionStrings>()
            .MainConnection;
}